Added new allocation status "Active (Needs Renewal)"
nerc-project/coldfront-nerc pull request #121
Opened 2024-06-12 12:59 UTC by QuanMPhm

Closes #120. When any Coldfront expires, the allocation's status will change to "Active (Needs Renewal)" instead of "Expired"

2024-06-17 20:10 UTC, jtriley commented
@QuanMPhm we also need to include the patch in the Dockerfile:

https://github.com/nerc-project/coldfront-nerc/blob/main/Dockerfile#L30

2024-06-17 20:11 UTC, jtriley requested changes
@QuanMPhm we also need to include the patch in the Dockerfile:

https://github.com/nerc-project/coldfront-nerc/blob/main/Dockerfile#L30

2024-06-17 20:18 UTC, jtriley commented on patches/03_add_active_needs_renewal_status.patch
> +-        for choice in ('Active (Needs Renewal)', 'Active', 'Denied', 'Expired',
This patch looks to be the reverse of the change you're attempting to make...

2024-06-18 14:34 UTC, jtriley approved these changes

2024-06-18 14:34 UTC, jtriley commented
@QuanMPhm LGTM and approved but would like to wait for @knikolla review before merging. Thanks!!

2024-07-10 16:38 UTC, knikolla approved these changes
Looks good to me.

@QuanMPhm Have you had a chance to test that the `add_allocation_defaults` function works correctly when executed on a ColdFront that already has the allocation defaults?

2024-07-10 17:53 UTC, QuanMPhm commented
@knikolla When the patched command is ran on a Coldfront with the old defaults, the new `Active (Needs Renewal)` allocation status is added. I did not see any errors.

2024-07-26 13:12 UTC, joachimweyl commented
@QuanMPhm what are next steps to get this merged?

2024-07-26 15:19 UTC, QuanMPhm commented
@joachimweyl I suppose I'll merge it now. I was just waiting for someone with more seniority to merge it.

2024-07-26 15:19 UTC, merged